### ISSUE TITLE
`assert_c!` should be `unsafe_assert_c!`

### ISSUE THREAD

**Issue by tspiteri** [Hywan/inline-c-rs#1]
As it is, this would be an unsound library as it allows you to cause undefined behaviour with safe code. I believe simply inserting `unsafe` in the macro name would fix this: I recall seeing this in some threads about some macros doing unsafe things, though I cannot find anything.

**Comment by Hywan** [comment]
The macro does nothing unsafe. The C code does not exchange information or data with the Rust code, they are isolated :-).

**Comment by tspiteri** [comment]
Oh I see! So the C code is executed similar to how [`std::process::Command::status`](https://doc.rust-lang.org/std/process/struct.Command.html#method.status) executes an external program, and that method is safe.
