### ISSUE TITLE
Doesn't allow declaring C macros

### ISSUE THREAD

**Issue by sdroege** [Hywan/inline-c-rs#5]
```rust
use inline_c::assert_c;

fn main() {
    (assert_c! {
        #include <stdio.h>

        #define sum(a,b) ((a) + (b))

        int main() {
            printf("%d", sum(1, 2));

            return 0;
        }
    })
    .success()
    .stdout("Hello, World!");
}
```

This fails compiling the C code with

```
thread 'main' panicked at 'Unexpected failure.
code-1
stderr=```/tmp/inline-c-rs-9ZdBkB.c:5:9: error: expected declaration specifiers or ‘...’ before string constant
    5 | printf ("%d", sum (1, 2));
      |         ^~~~
/tmp/inline-c-rs-9ZdBkB.c:4:13: error: expected declaration specifiers or ‘...’ before ‘(’ token
    4 | #define sum (a , b )((a )+ (b ))int main (){
      |             ^
/tmp/inline-c-rs-9ZdBkB.c:5:15: note: in expansion of macro ‘sum’
    5 | printf ("%d", sum (1, 2));
      |               ^~~
/tmp/inline-c-rs-9ZdBkB.c:6:1: error: expected declaration specifiers or ‘...’ before ‘return’
    6 | return 0;
      | ^~~~~~
/tmp/inline-c-rs-9ZdBkB.c:8:1: error: expected declaration specifiers or ‘...’ before ‘}’ token
    8 | }
      | ^
/tmp/inline-c-rs-9ZdBkB.c:8:1: error: expected ‘;’, ‘,’ or ‘)’ before ‘}’ token
```
command=`"cc" "/tmp/inline-c-rs-9ZdBkB.c" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-Wall" "-Wextra" "-Werror" "-o" "/tmp/inline-c-rs-5lq9Fv"`
code=1
stdout=``````
stderr=```/tmp/inline-c-rs-9ZdBkB.c:5:9: error: expected declaration specifiers or ‘...’ before string constant
    5 | printf ("%d", sum (1, 2));
      |         ^~~~
/tmp/inline-c-rs-9ZdBkB.c:4:13: error: expected declaration specifiers or ‘...’ before ‘(’ token
    4 | #define sum (a , b )((a )+ (b ))int main (){
      |             ^
/tmp/inline-c-rs-9ZdBkB.c:5:15: note: in expansion of macro ‘sum’
    5 | printf ("%d", sum (1, 2));
      |               ^~~
/tmp/inline-c-rs-9ZdBkB.c:6:1: error: expected declaration specifiers or ‘...’ before ‘return’
    6 | return 0;
      | ^~~~~~
/tmp/inline-c-rs-9ZdBkB.c:8:1: error: expected declaration specifiers or ‘...’ before ‘}’ token
    8 | }
      | ^
/tmp/inline-c-rs-9ZdBkB.c:8:1: error: expected ‘;’, ‘,’ or ‘)’ before ‘}’ token
```
', /home/slomo/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.2/src/assert.rs:158:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by Hywan** [comment]
That's because the `define` declarative isn't reconstructed properly in `inline-c-macro`. I'll try to find time to fix that!

**Comment by Hywan** [comment]
Immediate workaround is to define the macro inside a `.h` file, and include that file. Not the most convenient solution, but it works.
