### ISSUE TITLE
LDFLAGS mapping breaks on msvc

### ISSUE THREAD

**Issue by lu-zero** [Hywan/inline-c-rs#8]
As seen on [here](https://github.com/lu-zero/cargo-c/pull/142)/[ci](https://github.com/lu-zero/cargo-c/pull/142/checks?check_run_id=1453623015#step:8:122):
```
stderr=```cl : Command line error D8021 : invalid numeric argument '/Wl,-LD:\a\cargo-c\cargo-c\example-project\target\.\release'
```

**Comment by Hywan** [comment]
Hello,

Thanks for the issue. I've no idea yet how MSVC is supposed to handle `LDFLAGS`. I'll check. Is it blocking for you?

**Comment by lu-zero** [comment]
I just passed everything through CFLAGS.

**Comment by Hywan** [comment]
OK. So I've time to find a proper solution, which starts by having a Windows VM somewhere :-D!

**Comment by Tim-Evans-Seequent** [comment]
For reference, the correct way to pass arguments to the linker via MSVC is via "/link". All arguments after /link are passed to the linker.

https://learn.microsoft.com/en-us/cpp/build/reference/compiler-command-line-syntax?view=msvc-170

**Comment by camio** [comment]
It looks like this issue was addressed by the wasmer project by forking this repository into https://github.com/wasmerio/inline-c. The package to use on cargo is https://crates.io/crates/wasmer-inline-c/0.1.2

**Comment by Hywan** [comment]
Be careful. [`wasmer-inline-c`](https://crates.io/crates/wasmer-inline-c/0.1.2) was a fork of this project, that is pointing to https://github.com/fschutt/wasmer-inline-c-rs, which is now dead. The first release was on September 2022. The attributions have even been corrected to reflect [it was a fork](https://github.com/wasmerio/inline-c/commit/ef0fe1c46a696c16c402f49e26fa7c799d496fc1).

Wasmer is trying to steal this project from me, and has created another fork https://github.com/wasmerio/inline-c (which apparently is a copy of https://github.com/fschutt/wasmer-inline-c-rs).

All this is unclear and I'm exchanging emails with Syrus Akbary (CEO of Wasmer) to try to protect my work. As soon as I've pointed him out that https://github.com/fschutt/wasmer-inline-c-rs was dead, he has created https://github.com/wasmerio/inline-c.

I don't want this fight. Syrus is claiming the ownership after 3-4 years. This is non-sense…

**Comment by Hywan** [comment]
It's even better than that.

So Syrus has put https://github.com/fschutt/wasmer-inline-c-rs back online at https://github.com/wasmerio/inline-c. It's interesting to read the commit history.

* First commit, https://github.com/wasmerio/inline-c/commit/1edacf7d9c7914598aa9ed070587a5e4a877190a, we see that fschutt (who was working at Wasmer at that time) has stolen my code. This first commit copies the `inline-c-macro` code, even with my name as the author (https://github.com/wasmerio/inline-c/commit/1edacf7d9c7914598aa9ed070587a5e4a877190a#diff-8f8d4d6e0fe204c781061cda8ccf902914990001e641e61ca2c7c181e386d4dbR6-R8). This first commit copies the `inline-c` code (the `run.rs` and `assert.rs` modules have been inlined, that's mostly it, https://github.com/wasmerio/inline-c/commit/1edacf7d9c7914598aa9ed070587a5e4a877190a#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759).
* Second commit (2 days later), https://github.com/wasmerio/inline-c/commit/ef0fe1c46a696c16c402f49e26fa7c799d496fc1. fschutt has clarified the author to restore my name,
* Third commit, https://github.com/wasmerio/inline-c/commit/0f0b3a6c3b57ea2a0af03a76044392765ca764fa, nothing was compiling so stuff had to be fixed.

Note that the `LICENSE.md` file has not been copied, here is my `LICENSE`, https://github.com/Hywan/inline-c-rs/blob/master/LICENSE.md.

Was Syrus aware? Probably, as he is co-owner on crates.io, https://crates.io/crates/wasmer-inline-c:

<img width="789" alt="Screenshot 2024-09-14 at 13 41 25" src="https://github.com/user-attachments/assets/4296906e-2ffd-4a75-b12b-7e6a2b90d54f">

At the time of writing (September 14th, 2024), he has not updated crates.io yet.

**Comment by camio** [comment]
The "wasmer-inline-c" fork, as far as I can tell, [works only for windows](https://github.com/wasmerio/wasmer/blob/c6c348d00fa3582eb3b3fda07e69fdc695156193/lib/c-api/Cargo.toml#L55-L59) and [removed the ability to run](https://github.com/wasmerio/inline-c/issues/1) inline C/C++ code. Wasmer's c-api code [switches between](https://github.com/wasmerio/wasmer/blob/c6c348d00fa3582eb3b3fda07e69fdc695156193/lib/c-api/src/wasm_c_api/instance.rs#L216-L219) the original inline-c and the fork based on platform detection.

Ideally there'd be one inline-c repository (Hywan/inline-c-rs) and it would have full support (execution included) for Windows. I'd be surprised if wasmer wouldn't switch to such a thing if that were in place. Would you accept a patch adding Windows support? I'm confident I could do it. We could also add a GitHub workflow that will verify this works as part of CI.

**Comment by Hywan** [comment]
I would definitely be happy with a patch for Windows support yeah. Feel free to provide one :-).
