### ISSUE TITLE
Object files left in source directory

### ISSUE THREAD

**Issue by Mikayex** [Hywan/inline-c-rs#9]
Hi !

I'm on Windows and I've a project with the following layout (nothing fancy, juste a workspace):
```
.
├── crate1/
│   └── Cargo.toml
├── crate2/
│   ├── tests/
│   │   └── hello.rs
│   ├── src/
│   │   └── ...
│   └── Cargo.toml
└── Cargo.toml
```

The file `hello.rs` has a test with `assert_c!` (just the hello world example from the readme)

# The problem
Compiled object files (.o/.obj) are created in `crate2/inline-c-rs-XXXXXX.obj`. A new one is created each time I run `cargo test`.

# The solution ?
I saw you used the `keep()` method on the temporary [input](https://github.com/Hywan/inline-c-rs/blob/7bd0f5e59f3e00534e0aeef1aeef6efe48804659/src/run.rs#L39) and [output](https://github.com/Hywan/inline-c-rs/blob/7bd0f5e59f3e00534e0aeef1aeef6efe48804659/src/run.rs#L47) files.

Would it be the cause ? I may be wrong, I just looked quickly...

**Comment by Hywan** [comment]
Hello,

It sounds weird because object files are created in the temp directory, not in the source tree. I didn't test the project on Windows except on the CI.

Also, the object files are kept but removed later… I think I've found the error. Let me try a fix!

**Comment by Hywan** [comment]
Can you test https://github.com/Hywan/inline-c-rs/pull/11 and tell me if it fixes your issue please?

**Comment by Mikayex** [comment]
No, it does not fix the problem.
However I've found the culprit ([from MSVC documentation](https://docs.microsoft.com/en-us/cpp/build/reference/fo-object-file-name?view=msvc-160)) :
> By default, the object files generated by the compiler are placed in the current directory. They're given the base name of the source file and a .obj extension.

So there is 2 ways to fix the problem : either compile in a temporary directory (which would work since absolute paths are used) and delete it after or use the `-Fo` option to explicitly set the object file output to a known file that we can delete after.

I can work on a PR for this if you want, just let me know what solution you prefer.

Also, I can reproduce it easily by running the tests on the crate, no need workspace. Maybe this can also be tested on CI by using the output of `git ls-files . --exclude-standard --others` ?

**Comment by Hywan** [comment]
That's weird because we are already using `-Fo`… ohh nooo, that was in a previous version of `inline-c-rs`. OK, I would greatly appreciate if you can submit a PR :-)!
